name: CI - Build Java & Create Podman Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Install Podman
        run: |
          sudo apt update
          sudo apt install -y podman
          podman --version

      - name: Build Container Image with Podman
        run: |
          podman build -t hotel-management-service:latest .

      - name: Save Podman Image to TAR
        run: podman save -o hotel-image.tar hotel-management-service:latest

      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: hotel-jar
          path: target/*.jar

