name: CI - Build Java & Push to GHCR

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Install Podman
        run: |
          sudo apt update
          sudo apt install -y podman
          podman --version

      - name: Build Container Image with Podman
        run: |
          podman build -t hotel-management-service:latest .

      - name: Upload Image TAR
        uses: actions/upload-artifact@v3
        with:
          name: hotel-image
          path: hotel-image.tar

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GHCR_PAT }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag Image for GHCR
        run: podman tag hotel-management-service ghcr.io/abhay-saste/hotel-management-service:latest

      - name: Push Image to GHCR
        run: podman push ghcr.io/abhay-saste/hotel-management-service:latest

